export const defaultStyles = {
  primaryColor: '#262626',
  guessedNumberBackground: '#262626',
  cardBackgroundColor: '#ece6b1',
  guessedNumberColor: '#fff',
  guessedNumberBorder: '#262626',
  inputTextColor: '#cccccc',
  labelColor: '#cccccc',
  borderColor: '#cccccc',
  shadowColor: '#262626',
  buttonTextColor: '#ffffff',
  buttonColor: '#5a5a5a',
  buttonEffectColor: '#3a3a3a',
  backgroundColor: '#5e7c88',
  backgroundLinearColor: '#e1ffa8',
  accentTextColor: '#262626',
  successColor: '#bfecb1',
  errorColor: '#ecb1b1',
  contrastColor: '#ffffff',
  buttonBackgroundColor: '#ece6b1',
  highlightedColor: '#262626',
  fontFamily: 'Poppins_400Regular',
  fontFamilyItalic: 'Poppins_400Regular_Italic',
};
